Repository Frictionless-Faction/FricFracChat, pull requests merged in 2021-07, with the labels that each got.

#10 Update README.md
  README.md
Labels: enhancement

#15 Feature/14 added routing via react
  package-lock.json
  package.json
  src/App.js
  src/pages/About.js
  src/pages/Chat.js
Labels: enhancement

#19 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#49 Update Home.js
  src/pages/Home.js
Labels: bug

#52 Bug/51
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/App.test.js
  src/css/About.module.css
  src/css/Chat.module.css
  src/css/Footer.css
  src/css/Home.module.css
  src/css/Sign-In.module.css
  src/pages/About.js
  src/pages/Chat.js
  src/pages/Footer.js
  src/pages/Home.js
Labels: bug

#48 #47 added yml config
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  firebase.json
  frictionless-faction/404.html
  frictionless-faction/index.html
Labels: enhancement
